# Use the Gazebo image as base
FROM ros:humble-ros-core

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Environment
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble

# Install SLAM and Navigation2 necessary dependencies for cartographer-ros package
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \ 
    ros-humble-tf2-ros \
    ros-humble-tf2-geometry-msgs \
    ros-humble-diagnostic-updater \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-xacro \
    ros-${ROS_DISTRO}-slam-toolbox \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-navigation2 \
    ros-${ROS_DISTRO}-rviz2 \
    ros-humble-cartographer \
    ros-humble-cartographer-ros \
    libpcap-dev \
    libpcap0.8 \
    && rm -rf /var/lib/apt/lists/*

RUN source /opt/ros/humble/setup.bash

# Clone the repositories for the project
WORKDIR /root/ros2_ws/src
COPY fastbot_navigation/ /root/ros2_ws/src

# Create workspace if not already there
WORKDIR /root/ros2_ws

# Build the Colcon workspace and ensure it's sourced
RUN source /opt/ros/humble/setup.bash \
    && cd /root/ros2_ws \
    && colcon build

# RUN echo "source /root/ros2_ws/install/setup.bash" >> ~/.bashrc

# Default command for testing (override with docker-compose or at runtime)
# Source the built workspace and set the entrypoint to run the package
ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && source /root/ros2_ws/install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"]
